### ISSUE TITLE
Problema pale 

### ISSUE THREAD

**Issue by FrancescoGiacomoPalermo05** [profradaelli/ProveJava4B#11]
i have i problem with the program

**Comment by Stoicanescu-Eliza-Stefania** [comment]
the professor says you have to take care of yourself. Sorry

**Comment by AdrianWitkowski0** [comment]
ciao palermo

**Comment by FrancescoGiacomoPalermo05** [comment]
ciao abrian ### 

- > [_****_]([url](url))
